using EventBooking.Data;
using EventBooking.Models;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using System.Threading;
using static System.Formats.Asn1.AsnWriter;

//Start building my web application and prepare all configurations,
//services, and settings before running it
var builder = WebApplication.CreateBuilder(args);

// Add services to the container

// Register the database context with SQL Server connection
builder.Services.AddDbContext<AppDbContext>(options =>
    options.UseSqlServer(builder.Configuration.GetConnectionString("DefaultConnection")));

// Configure ASP.NET Identity
builder.Services.AddIdentity<ApplicationUser, IdentityRole>(options =>
{
    // Password settings (relaxed for development)
    options.Password.RequireDigit = false;
    options.Password.RequireLowercase = false;
    options.Password.RequireUppercase = false;
    options.Password.RequireNonAlphanumeric = false;
    options.Password.RequiredLength = 6;

    // User settings
    options.User.RequireUniqueEmail = true;
})
.AddEntityFrameworkStores<AppDbContext>()
.AddDefaultTokenProviders();

// Configure cookie settings
builder.Services.ConfigureApplicationCookie(options =>
{
    options.LoginPath = "/Account/Login";
    options.LogoutPath = "/Account/Logout";
    options.AccessDeniedPath = "/Account/AccessDenied";
    options.Cookie.HttpOnly = true;
    options.ExpireTimeSpan = TimeSpan.FromDays(7);
});

// Add MVC controllers and views
builder.Services.AddControllersWithViews();

// Add HttpClient and switch to Gemini Chatbot Service
//Enable HTTP requests  -> Whenever app asks for IChatbotService
//-> Give it GeminiChatbotService
//HttpClient is used to send HTTP requests to external APIs.
//Scoped lifetime means: Create ONE instance per HTTP request.
//Other lifetimes: AddTransient	-> new object every time, AddScoped -> one per request, AddSingleton ->	one for whole app
//Whenever someone asks for IChatbotService, create a GeminiChatbotService
builder.Services.AddHttpClient();
builder.Services.AddScoped<EventBooking.Services.IChatbotService, EventBooking.Services.GeminiChatbotService>();

var app = builder.Build();

//1. Open a service scope
//2.Get database services
//3. Update database schema
//4. Create roles if missing
//5. Create admin account if missing
// Apply pending migrations and seed data automatically on startup
//using (var scope = app.Services.CreateScope()) Create a temporary Dependency Injection scope.
//Services like: AppDbContext, UserManager, RoleManager are registered as scoped services.
//Scoped services must live inside a scope.
//this code runs: at startup ,outside requests So we manually create one.
//A scope is a temporary container/session where scoped services live.
using (var scope = app.Services.CreateScope())
{
    //scope.ServiceProvider This object knows all registered services.
    //Create or get an object whose TYPE is AppDbContext
    //context is NOT the database itself. It is: an object that COMMUNICATES with
    //the database.
    var context = scope.ServiceProvider.GetRequiredService<AppDbContext>();

    //updates the actual SQL database schema to match your current Entity Framework
    //Core models and migrations.
    //Migrations are database updates generated by EF Core.
    context.Database.Migrate();

    // Seed admin role and admin user
    //Gets the Identity role manager service.
    //What does RoleManager do? Handles roles like: Admin, User, Organizer
    //Operations: create roles, delete roles, check existence
    var roleManager = scope.ServiceProvider.GetRequiredService<RoleManager<IdentityRole>>();

    //Gets the Identity user manager service.
    var userManager = scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();

    // Create roles
    string[] roles = { "Admin", "User" };
    foreach (var role in roles)
    {
        //Why await? Because database operations are asynchronous.
        //The app waits for database response without blocking thread.
        if (!await roleManager.RoleExistsAsync(role)) //Does this role already exist?
        {
            //Step 1  Create object IdentityRole("Admin") -> memory object
            //Step 2  RoleManager receives it
            //Step 3  EF Core mapping: IdentityRole -> mapped to AspNetRoles table
            await roleManager.CreateAsync(new IdentityRole(role));
        }
    }

    // Create default admin user
    var adminEmail = "admin@eventbooking.com";
    // Only create admin if it doesn’t already exist
    if (await userManager.FindByEmailAsync(adminEmail) == null)
    {
        //Create ApplicationUser object in memory. NOT saved yet.
        var admin = new ApplicationUser
        {
            UserName = adminEmail,
            Email = adminEmail,
            FullName = "System Admin",
            EmailConfirmed = true,
            City = "New York"
        };
        //validates user, hashes password, saves user to database
        var result = await userManager.CreateAsync(admin, "Admin123");

        if (result.Succeeded) //Check if creation succeeded
        {
            //Assign Admin role to user. this user now has admin permissions.
            await userManager.AddToRoleAsync(admin, "Admin");
        }
    }
}

// Configure the HTTP request pipeline
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Home/Error");
}

app.UseStaticFiles();
app.UseRouting();

// Authentication must come before Authorization
app.UseAuthentication();
app.UseAuthorization();

// Default route configuration
app.MapControllerRoute(
    name: "default",
    pattern: "{controller=Home}/{action=Index}/{id?}");

app.Run();
