// <auto-generated />
using System;
using EventBooking.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventBooking.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260507184050_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventBooking.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("TicketCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("EventBooking.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableTickets")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableTickets = 500,
                            Date = new DateTime(2026, 7, 15, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Join us for an unforgettable summer music festival featuring top artists from around the world. Enjoy live performances, food trucks, and an amazing atmosphere under the stars. This three-day event will feature multiple stages with genres ranging from rock and pop to electronic and indie music.",
                            ImageUrl = "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800&h=500&fit=crop",
                            Location = "Central Park, New York",
                            Price = 75.00m,
                            Title = "Summer Music Festival"
                        },
                        new
                        {
                            Id = 2,
                            AvailableTickets = 300,
                            Date = new DateTime(2026, 8, 20, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Explore the latest in technology and innovation at our annual conference. Hear from industry leaders, attend hands-on workshops, and network with professionals. Topics include AI, cloud computing, cybersecurity, and the future of software development.",
                            ImageUrl = "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&h=500&fit=crop",
                            Location = "Convention Center, San Francisco",
                            Price = 120.00m,
                            Title = "Tech Innovation Conference"
                        },
                        new
                        {
                            Id = 3,
                            AvailableTickets = 200,
                            Date = new DateTime(2026, 9, 10, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Indulge in an evening of exquisite cuisine and fine wines from renowned chefs and vineyards. This elegant gala features a five-course tasting menu paired with premium wines, live jazz music, and an exclusive cooking demonstration.",
                            ImageUrl = "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&h=500&fit=crop",
                            Location = "Grand Ballroom, Chicago",
                            Price = 95.00m,
                            Title = "Food & Wine Tasting Gala"
                        },
                        new
                        {
                            Id = 4,
                            AvailableTickets = 1000,
                            Date = new DateTime(2026, 10, 5, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Challenge yourself in our annual city marathon! Whether you're a seasoned runner or a beginner, join thousands of participants running through scenic city routes. The event includes a full marathon, half marathon, and a fun 5K run for families.",
                            ImageUrl = "https://images.unsplash.com/photo-1532444458054-01a7dd3e9fca?w=800&h=500&fit=crop",
                            Location = "Downtown, Boston",
                            Price = 45.00m,
                            Title = "Marathon City Run"
                        },
                        new
                        {
                            Id = 5,
                            AvailableTickets = 150,
                            Date = new DateTime(2026, 11, 12, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Discover stunning works of art and photography from emerging and established artists. This curated exhibition showcases contemporary pieces in painting, sculpture, digital art, and photography. Meet the artists and enjoy guided tours throughout the day.",
                            ImageUrl = "https://images.unsplash.com/photo-1531243269054-5ebf6f34081e?w=800&h=500&fit=crop",
                            Location = "Modern Art Gallery, Los Angeles",
                            Price = 30.00m,
                            Title = "Art & Photography Exhibition"
                        },
                        new
                        {
                            Id = 6,
                            AvailableTickets = 250,
                            Date = new DateTime(2026, 12, 1, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Get ready for a night of non-stop laughter with some of the funniest comedians in the business. Our Comedy Night Live event features stand-up performances, improv shows, and audience participation segments that will keep you entertained all evening.",
                            ImageUrl = "https://images.unsplash.com/photo-1527224538127-2104bb71c51b?w=800&h=500&fit=crop",
                            Location = "Laugh Factory, Las Vegas",
                            Price = 55.00m,
                            Title = "Comedy Night Live"
                        });
                });

            modelBuilder.Entity("EventBooking.Models.Booking", b =>
                {
                    b.HasOne("EventBooking.Models.Event", "Event")
                        .WithMany("Bookings")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("EventBooking.Models.Event", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
