// <auto-generated />
using System;
using EventBooking.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventBooking.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260507191707_AdvancedEventFeatures")]
    partial class AdvancedEventFeatures
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventBooking.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("EventBooking.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TicketCount")
                        .HasColumnType("int");

                    b.Property<int?>("TicketTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("TicketTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("EventBooking.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Concerts, festivals, and live music performances",
                            Icon = "bi-music-note-beamed",
                            ImageUrl = "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=600&h=400&fit=crop",
                            Name = "Music",
                            Slug = "music"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Tech conferences, hackathons, and innovation summits",
                            Icon = "bi-cpu",
                            ImageUrl = "https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&h=400&fit=crop",
                            Name = "Technology",
                            Slug = "technology"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Marathons, tournaments, and sporting events",
                            Icon = "bi-trophy",
                            ImageUrl = "https://images.unsplash.com/photo-1461896836934-bd45ba24e4c7?w=600&h=400&fit=crop",
                            Name = "Sports",
                            Slug = "sports"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Food festivals, wine tastings, and culinary experiences",
                            Icon = "bi-cup-straw",
                            ImageUrl = "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&h=400&fit=crop",
                            Name = "Food & Drink",
                            Slug = "food-drink"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Art exhibitions, theater performances, and cultural shows",
                            Icon = "bi-palette",
                            ImageUrl = "https://images.unsplash.com/photo-1531243269054-5ebf6f34081e?w=600&h=400&fit=crop",
                            Name = "Arts & Theater",
                            Slug = "arts-theater"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Hands-on workshops, training sessions, and skill-building events",
                            Icon = "bi-tools",
                            ImageUrl = "https://images.unsplash.com/photo-1552664730-d307ca884978?w=600&h=400&fit=crop",
                            Name = "Workshops",
                            Slug = "workshops"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Stand-up comedy shows, improv nights, and comedy festivals",
                            Icon = "bi-emoji-laughing",
                            ImageUrl = "https://images.unsplash.com/photo-1527224538127-2104bb71c51b?w=600&h=400&fit=crop",
                            Name = "Comedy",
                            Slug = "comedy"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Professional conferences, seminars, and networking events",
                            Icon = "bi-people",
                            ImageUrl = "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=600&h=400&fit=crop",
                            Name = "Conferences",
                            Slug = "conferences"
                        });
                });

            modelBuilder.Entity("EventBooking.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableTickets")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RecurrenceRule")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableTickets = 500,
                            CategoryId = 1,
                            City = "New York",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2026, 7, 15, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Join us for an unforgettable summer music festival featuring top artists from around the world. Enjoy live performances, food trucks, and an amazing atmosphere under the stars. This three-day event will feature multiple stages with genres ranging from rock and pop to electronic and indie music.",
                            EndDate = new DateTime(2026, 7, 17, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800&h=500&fit=crop",
                            IsFeatured = true,
                            Location = "Central Park, New York",
                            MaxCapacity = 500,
                            Price = 75.00m,
                            Title = "Summer Music Festival"
                        },
                        new
                        {
                            Id = 2,
                            AvailableTickets = 300,
                            CategoryId = 2,
                            City = "San Francisco",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2026, 8, 20, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Explore the latest in technology and innovation at our annual conference. Hear from industry leaders, attend hands-on workshops, and network with professionals. Topics include AI, cloud computing, cybersecurity, and the future of software development.",
                            EndDate = new DateTime(2026, 8, 21, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&h=500&fit=crop",
                            IsFeatured = true,
                            Location = "Convention Center, San Francisco",
                            MaxCapacity = 300,
                            Price = 120.00m,
                            Title = "Tech Innovation Conference"
                        },
                        new
                        {
                            Id = 3,
                            AvailableTickets = 200,
                            CategoryId = 4,
                            City = "Chicago",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2026, 9, 10, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Indulge in an evening of exquisite cuisine and fine wines from renowned chefs and vineyards. This elegant gala features a five-course tasting menu paired with premium wines, live jazz music, and an exclusive cooking demonstration.",
                            EndDate = new DateTime(2026, 9, 10, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&h=500&fit=crop",
                            IsFeatured = true,
                            Location = "Grand Ballroom, Chicago",
                            MaxCapacity = 200,
                            Price = 95.00m,
                            Title = "Food & Wine Tasting Gala"
                        },
                        new
                        {
                            Id = 4,
                            AvailableTickets = 1000,
                            CategoryId = 3,
                            City = "Boston",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2026, 10, 5, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Challenge yourself in our annual city marathon! Whether you're a seasoned runner or a beginner, join thousands of participants running through scenic city routes. The event includes a full marathon, half marathon, and a fun 5K run for families.",
                            EndDate = new DateTime(2026, 10, 5, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1532444458054-01a7dd3e9fca?w=800&h=500&fit=crop",
                            IsFeatured = false,
                            Location = "Downtown, Boston",
                            MaxCapacity = 1000,
                            Price = 45.00m,
                            Title = "Marathon City Run"
                        },
                        new
                        {
                            Id = 5,
                            AvailableTickets = 150,
                            CategoryId = 5,
                            City = "Los Angeles",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2026, 11, 12, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Discover stunning works of art and photography from emerging and established artists. This curated exhibition showcases contemporary pieces in painting, sculpture, digital art, and photography. Meet the artists and enjoy guided tours throughout the day.",
                            EndDate = new DateTime(2026, 11, 14, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1531243269054-5ebf6f34081e?w=800&h=500&fit=crop",
                            IsFeatured = false,
                            Location = "Modern Art Gallery, Los Angeles",
                            MaxCapacity = 150,
                            Price = 30.00m,
                            Title = "Art & Photography Exhibition"
                        },
                        new
                        {
                            Id = 6,
                            AvailableTickets = 250,
                            CategoryId = 7,
                            City = "Las Vegas",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2026, 12, 1, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Get ready for a night of non-stop laughter with some of the funniest comedians in the business. Our Comedy Night Live event features stand-up performances, improv shows, and audience participation segments that will keep you entertained all evening.",
                            EndDate = new DateTime(2026, 12, 1, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1527224538127-2104bb71c51b?w=800&h=500&fit=crop",
                            IsFeatured = false,
                            Location = "Laugh Factory, Las Vegas",
                            MaxCapacity = 250,
                            Price = 55.00m,
                            Title = "Comedy Night Live"
                        },
                        new
                        {
                            Id = 7,
                            AvailableTickets = 120,
                            CategoryId = 1,
                            City = "New York",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2026, 8, 5, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Experience an intimate evening of world-class jazz at the legendary Blue Note venue. Featuring acclaimed jazz musicians performing classic standards and original compositions. Enjoy cocktails and small plates while immersing yourself in smooth jazz melodies.",
                            EndDate = new DateTime(2026, 8, 5, 23, 30, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=800&h=500&fit=crop",
                            IsFeatured = false,
                            Location = "Blue Note Jazz Club, New York",
                            MaxCapacity = 120,
                            Price = 65.00m,
                            RecurrenceRule = "Every Tuesday",
                            Title = "Jazz Night at Blue Note"
                        },
                        new
                        {
                            Id = 8,
                            AvailableTickets = 50,
                            CategoryId = 6,
                            City = "San Francisco",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2026, 9, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A hands-on workshop for aspiring web developers. Learn HTML, CSS, JavaScript, and modern frameworks from experienced instructors. Build a real project by the end of the day and leave with new skills to advance your career in tech.",
                            EndDate = new DateTime(2026, 9, 1, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&h=400&fit=crop",
                            IsFeatured = false,
                            Location = "Tech Hub, San Francisco",
                            MaxCapacity = 50,
                            Price = 0.00m,
                            Title = "Web Development Workshop"
                        },
                        new
                        {
                            Id = 9,
                            AvailableTickets = 400,
                            CategoryId = 8,
                            City = "Chicago",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2026, 10, 15, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Join top business leaders and entrepreneurs at this premier conference. Sessions cover leadership strategies, market trends, digital transformation, and sustainable business practices. Network with 500+ professionals and gain actionable insights.",
                            EndDate = new DateTime(2026, 10, 16, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=800&h=500&fit=crop",
                            IsFeatured = true,
                            Location = "Hilton Conference Center, Chicago",
                            MaxCapacity = 400,
                            Price = 250.00m,
                            Title = "Business Leadership Summit"
                        },
                        new
                        {
                            Id = 10,
                            AvailableTickets = 800,
                            CategoryId = 1,
                            City = "New York",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2026, 11, 20, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The Amplifiers are back with their world tour! Don't miss their electrifying live performance featuring hits from their latest album. Special guest opening acts and an incredible light show make this a must-attend event for rock music fans.",
                            EndDate = new DateTime(2026, 11, 20, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&h=500&fit=crop",
                            IsFeatured = true,
                            Location = "Madison Square Garden, New York",
                            MaxCapacity = 800,
                            Price = 150.00m,
                            Title = "Rock Concert: The Amplifiers"
                        });
                });

            modelBuilder.Entity("EventBooking.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("EventBooking.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("CardLast4")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("EventBooking.Models.SavedEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId", "EventId")
                        .IsUnique();

                    b.ToTable("SavedEvents");
                });

            modelBuilder.Entity("EventBooking.Models.TicketType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableCount")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("TicketTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableCount = 350,
                            Description = "General admission",
                            EventId = 1,
                            Name = "Standard",
                            Price = 75.00m,
                            Quantity = 350
                        },
                        new
                        {
                            Id = 2,
                            AvailableCount = 100,
                            Description = "Front row access + backstage pass",
                            EventId = 1,
                            Name = "VIP",
                            Price = 150.00m,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 3,
                            AvailableCount = 50,
                            Description = "Valid student ID required",
                            EventId = 1,
                            Name = "Student",
                            Price = 45.00m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 4,
                            AvailableCount = 200,
                            Description = "All sessions access",
                            EventId = 2,
                            Name = "Standard",
                            Price = 120.00m,
                            Quantity = 200
                        },
                        new
                        {
                            Id = 5,
                            AvailableCount = 50,
                            Description = "All sessions + speaker dinner + networking lounge",
                            EventId = 2,
                            Name = "VIP",
                            Price = 250.00m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 6,
                            AvailableCount = 50,
                            Description = "Valid student ID required",
                            EventId = 2,
                            Name = "Student",
                            Price = 60.00m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 7,
                            AvailableCount = 150,
                            Description = "Full tasting menu",
                            EventId = 3,
                            Name = "Standard",
                            Price = 95.00m,
                            Quantity = 150
                        },
                        new
                        {
                            Id = 8,
                            AvailableCount = 50,
                            Description = "Premium wines + chef meet & greet",
                            EventId = 3,
                            Name = "VIP",
                            Price = 180.00m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 9,
                            AvailableCount = 500,
                            Description = "42.2km full marathon",
                            EventId = 4,
                            Name = "Full Marathon",
                            Price = 45.00m,
                            Quantity = 500
                        },
                        new
                        {
                            Id = 10,
                            AvailableCount = 300,
                            Description = "21.1km half marathon",
                            EventId = 4,
                            Name = "Half Marathon",
                            Price = 30.00m,
                            Quantity = 300
                        },
                        new
                        {
                            Id = 11,
                            AvailableCount = 200,
                            Description = "Family-friendly 5K",
                            EventId = 4,
                            Name = "5K Fun Run",
                            Price = 15.00m,
                            Quantity = 200
                        },
                        new
                        {
                            Id = 12,
                            AvailableCount = 100,
                            Description = "General admission",
                            EventId = 5,
                            Name = "Standard",
                            Price = 30.00m,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 13,
                            AvailableCount = 50,
                            Description = "Guided tour + artist meet",
                            EventId = 5,
                            Name = "VIP",
                            Price = 60.00m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 14,
                            AvailableCount = 200,
                            Description = "General seating",
                            EventId = 6,
                            Name = "Standard",
                            Price = 55.00m,
                            Quantity = 200
                        },
                        new
                        {
                            Id = 15,
                            AvailableCount = 50,
                            Description = "Front row + meet comedians",
                            EventId = 6,
                            Name = "VIP",
                            Price = 100.00m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 16,
                            AvailableCount = 80,
                            Description = "Table seating",
                            EventId = 7,
                            Name = "Standard",
                            Price = 65.00m,
                            Quantity = 80
                        },
                        new
                        {
                            Id = 17,
                            AvailableCount = 40,
                            Description = "Premium table + complimentary drinks",
                            EventId = 7,
                            Name = "VIP",
                            Price = 120.00m,
                            Quantity = 40
                        },
                        new
                        {
                            Id = 18,
                            AvailableCount = 50,
                            Description = "Free workshop seat",
                            EventId = 8,
                            Name = "Free Registration",
                            Price = 0.00m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 19,
                            AvailableCount = 300,
                            Description = "All sessions",
                            EventId = 9,
                            Name = "Standard",
                            Price = 250.00m,
                            Quantity = 300
                        },
                        new
                        {
                            Id = 20,
                            AvailableCount = 100,
                            Description = "All sessions + executive lounge + keynote dinner",
                            EventId = 9,
                            Name = "VIP",
                            Price = 500.00m,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 21,
                            AvailableCount = 500,
                            Description = "General admission",
                            EventId = 10,
                            Name = "Standard",
                            Price = 150.00m,
                            Quantity = 500
                        },
                        new
                        {
                            Id = 22,
                            AvailableCount = 200,
                            Description = "Floor access + exclusive merch",
                            EventId = 10,
                            Name = "VIP",
                            Price = 300.00m,
                            Quantity = 200
                        },
                        new
                        {
                            Id = 23,
                            AvailableCount = 100,
                            Description = "Valid student ID required",
                            EventId = 10,
                            Name = "Student",
                            Price = 90.00m,
                            Quantity = 100
                        });
                });

            modelBuilder.Entity("EventBooking.Models.UserEventHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ViewedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("UserEventHistories");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EventBooking.Models.Booking", b =>
                {
                    b.HasOne("EventBooking.Models.Event", "Event")
                        .WithMany("Bookings")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventBooking.Models.TicketType", "TicketType")
                        .WithMany("Bookings")
                        .HasForeignKey("TicketTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EventBooking.Models.ApplicationUser", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Event");

                    b.Navigation("TicketType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventBooking.Models.Event", b =>
                {
                    b.HasOne("EventBooking.Models.Category", "Category")
                        .WithMany("Events")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EventBooking.Models.Order", b =>
                {
                    b.HasOne("EventBooking.Models.Booking", "Booking")
                        .WithOne("Order")
                        .HasForeignKey("EventBooking.Models.Order", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventBooking.Models.ApplicationUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Booking");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventBooking.Models.Payment", b =>
                {
                    b.HasOne("EventBooking.Models.Booking", "Booking")
                        .WithOne("Payment")
                        .HasForeignKey("EventBooking.Models.Payment", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("EventBooking.Models.SavedEvent", b =>
                {
                    b.HasOne("EventBooking.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventBooking.Models.ApplicationUser", "User")
                        .WithMany("SavedEvents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventBooking.Models.TicketType", b =>
                {
                    b.HasOne("EventBooking.Models.Event", "Event")
                        .WithMany("TicketTypes")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("EventBooking.Models.UserEventHistory", b =>
                {
                    b.HasOne("EventBooking.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventBooking.Models.ApplicationUser", "User")
                        .WithMany("BrowsingHistory")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("EventBooking.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("EventBooking.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventBooking.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("EventBooking.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventBooking.Models.ApplicationUser", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("BrowsingHistory");

                    b.Navigation("Orders");

                    b.Navigation("SavedEvents");
                });

            modelBuilder.Entity("EventBooking.Models.Booking", b =>
                {
                    b.Navigation("Order");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("EventBooking.Models.Category", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("EventBooking.Models.Event", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("TicketTypes");
                });

            modelBuilder.Entity("EventBooking.Models.TicketType", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
